# EXCEL a SQL

En este archivo vamos a crear inserts de SQL a partir de datos de un Excel.

Vamos a seguir varios pasos:

+ Instalar dependencias nuevas.
+ Llenar tablas fuertes
+ Llenar tablas débiles

### Importación de librerías

In [1]:
import pandas as pd
import numpy as np
from database import Database

db = Database('db/app.db')

### Ruta global y lectura del dataset

In [2]:
BASE_PATH = ''
doctors = pd.read_excel('datos.xlsx', sheet_name='doctors')
patients = pd.read_excel('datos.xlsx', sheet_name='patients')
treatments = pd.read_excel('datos.xlsx', sheet_name='treatments')
appointments = pd.read_excel('datos.xlsx', sheet_name='appointments')
billing = pd.read_excel('datos.xlsx', sheet_name='billing')

#### Lista de Doctores

In [35]:
doctors

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com
5,D006,Alex,Davis,Pediatrics,6570137231,23,Central Hospital,dr.alex.davis@hospital.com
6,D007,Robert,Davis,Oncology,8217493115,26,Westside Clinic,dr.robert.davis@hospital.com
7,D008,Linda,Brown,Dermatology,9069162601,5,Westside Clinic,dr.linda.brown@hospital.com
8,D009,Sarah,Smith,Pediatrics,7387087517,26,Central Hospital,dr.sarah.smith@hospital.com
9,D010,Linda,Wilson,Oncology,6176383634,21,Eastside Clinic,dr.linda.wilson@hospital.com

## Generación de Inserts
### Entidades fuertes

### Providers
Listar los proveedores de los pacientes sin repeticiones

In [7]:
tmp = patients['insurance_provider']
providers = list(tmp.unique())
providers

['WellnessCorp', 'PulseSecure', 'HealthIndia', 'MedCare Plus']

In [8]:
text = '-- migrate:up \n\n'
id = 1
for n in providers:
  text = text + f"INSERT INTO providers (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM providers;'
with open('inserts_providers.sql', 'w') as archivo:
  archivo.write(text)

### Payment_Statuses
Listar los estados de pago de los pacientes sin repeticiones

In [10]:
tmp = billing['payment_status']
payment_statuses = list(tmp.unique())
payment_statuses

['Pending', 'Paid', 'Failed']

In [11]:
text = '-- migrate:up \n\n'
id = 1
for n in payment_statuses:
  text = text + f"INSERT INTO payment_statuses (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM payment_statuses;'
with open('inserts_payment_statuses.sql', 'w') as archivo:
  archivo.write(text)

### Treatment_descriptions
Listar las descripciones de los tratamientos a los clientes

In [13]:
tmp = treatments['description']
treament_descriptions = list(tmp.unique())
treament_descriptions

['Basic screening', 'Advanced protocol', 'Standard procedure']

In [14]:
text = '-- migrate:up \n\n'
id = 1
for n in treament_descriptions:
  text = text + f"INSERT INTO treament_descriptions (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM treament_descriptions;'
with open('inserts_treament_descriptions.sql', 'w') as archivo:
  archivo.write(text)

### Treatment_types
Listar los tipos de tratamientos que reciben los clientes

In [15]:
tmp = treatments['treatment_type']
treatment_types = list(tmp.unique())
treatment_types

['Chemotherapy', 'MRI', 'ECG', 'Physiotherapy', 'X-Ray']

In [16]:
text = '-- migrate:up \n\n'
id = 1
for n in treatment_types:
  text = text + f"INSERT INTO treatment_types (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM treatment_types;'
with open('inserts_treatment_types.sql', 'w') as archivo:
  archivo.write(text)

### Appointment_reasons
Listar las razones de cita de los clientes sin repeticiones

In [18]:
tmp = appointments['reason_for_visit']
appointment_reasons = list(tmp.unique())
appointment_reasons

['Therapy', 'Consultation', 'Emergency', 'Checkup', 'Follow-up']

In [19]:
text = '-- migrate:up \n\n'
id = 1
for n in appointment_reasons:
  text = text + f"INSERT INTO appointment_reasons (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM appointment_reasons;'
with open('inserts_appointment_reasons.sql', 'w') as archivo:
  archivo.write(text)

### Appointment_statuses
Listar los estados de cita de los clientes sin repeticiones

In [20]:
tmp = appointments['status']
appointment_statuses = list(tmp.unique())
appointment_statuses

['Scheduled', 'No-show', 'Cancelled', 'Completed']

In [21]:
text = '-- migrate:up \n\n'
id = 1
for n in appointment_statuses:
  text = text + f"INSERT INTO appointment_statuses (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM appointment_statuses;'
with open('inserts_appointment_statuses.sql', 'w') as archivo:
  archivo.write(text)

### Hospital_branches
Listar las zonas del hospital sin repeticiones

In [23]:
tmp = doctors['hospital_branch']
hospital_branches = list(tmp.unique())
hospital_branches

['Westside Clinic', 'Eastside Clinic', 'Central Hospital']

In [31]:
text = '-- migrate:up \n\n'
id = 1
for n in hospital_branches:
  text = text + f"INSERT INTO hospital_branches (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM hospital_branches;'
with open('inserts_hospital_branches.sql', 'w') as archivo:
  archivo.write(text)

### Specializations
Listar las especializaciones de cada doctor sin repeticiones

In [25]:
tmp = doctors['specialization']
specializations = list(tmp.unique())
specializations

['Dermatology', 'Pediatrics', 'Oncology']

In [26]:
text = '-- migrate:up \n\n'
id = 1
for n in specializations:
  text = text + f"INSERT INTO specializations (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM specializations;'
with open('inserts_specializations.sql', 'w') as archivo:
  archivo.write(text)

### Genders
Listar los generos de cada persona sin repeticiones

In [28]:
tmp = patients['gender']
genders = list(tmp.unique())
genders

['F', 'M']

In [29]:
text = '-- migrate:up \n\n'
id = 1
for n in genders:
  text = text + f"INSERT INTO genders (id, name) VALUES ({id}, '{n}');\n"
  id = id + 1
text = text + '\n-- migrate:down \n\nDELETE FROM genders;'
with open('inserts_genders.sql', 'w') as archivo:
  archivo.write(text)

## Generación de Inserts
### Entidades debiles

### People
Listar las caracteristicas en comun que tiene una persona

In [3]:
tmpPatients = patients[['first_name','last_name','email']]
tmpDoctors = doctors[['first_name','last_name','email']]
tmpDoctors

  first_name last_name                         email
0      David    Taylor  dr.david.taylor@hospital.com
1       Jane     Davis    dr.jane.davis@hospital.com
2       Jane     Smith    dr.jane.smith@hospital.com
3      David     Jones   dr.david.jones@hospital.com
4      Sarah    Taylor  dr.sarah.taylor@hospital.com
5       Alex     Davis    dr.alex.davis@hospital.com
6     Robert     Davis  dr.robert.davis@hospital.com
7      Linda     Brown   dr.linda.brown@hospital.com
8      Sarah     Smith   dr.sarah.smith@hospital.com
9      Linda    Wilson  dr.linda.wilson@hospital.com

In [4]:
text = '-- migrate:up \n\n'
id = 1
# DOCTORES
for _, row in tmpPatients.iterrows():
 firstName = row['first_name']
 lastName = row['last_name']
 emailD = row['email']
 text = text + f"INSERT INTO people (id, first_name, last_name, email) VALUES ({id}, '{firstName}', '{lastName}', '{emailD}');\n"
 id = id + 1

# PACIENTES
for _, row in tmpPatients.iterrows():
 firstName = row['first_name']
 lastName = row['last_name']
 emailD = row['email']
 text = text + f"INSERT INTO people (id, first_name, last_name, email) VALUES ({id}, '{firstName}', '{lastName}', '{emailD}');\n"
 id = id + 1

text = text + '\n-- migrate:down \n\nDELETE FROM people;'
with open('inserts_people.sql', 'w') as archivo:
 archivo.write(text)